'use client';
import {useEffect,useRef,useState} from 'react';
export function Core({state='idle',level=0,intensity=1,variant='core'}:{state?:string;level?:number;intensity?:number;variant?:'core'|'face'}){
 const canvas=useRef<HTMLCanvasElement>(null),amplitude=useRef(level);amplitude.current=level;
 const [mesh,setMesh]=useState<{v:number[][];f:number[][]}|null>(null);
 useEffect(()=>{if(variant!=='face'||mesh)return;fetch('/face_model.obj').then(r=>r.text()).then(text=>{const v:number[][]=[],f:number[][]=[];for(const line of text.split('\n')){const parts=line.trim().split(/\s+/);if(parts[0]==='v')v.push(parts.slice(1,4).map(Number));if(parts[0]==='f')f.push(parts.slice(1,4).map(p=>Number(p.split('/')[0])-1));}setMesh({v,f})}).catch(()=>{});},[variant,mesh]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;let frame=0;let raf=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)intensity=0;
 const draw=()=>{if(document.hidden){raf=requestAnimationFrame(draw);return;}const w=c.clientWidth,h=c.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const x=w/2,y=h/2,r=Math.min(w,h)*.32,t=frame*.002*intensity,active=['thinking','executing'].includes(state),warm=state==='error';
 const color=warm?'242,169,81':'51,214,244';const glow=ctx.createRadialGradient(x,y,r*.1,x,y,r*1.5);glow.addColorStop(0,`rgba(${color},.08)`);glow.addColorStop(.65,`rgba(${color},.04)`);glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
 if(variant==='face'&&mesh){const turn=.25+Math.sin(t)*.12,scale=Math.min(w/25,h/25),points=mesh.v.map(([a,b,z])=>{const mouth=b<-2&&Math.abs(a)<3?Math.max(0,amplitude.current)*(Math.abs(b+2)/5):0;return [x+(a*Math.cos(turn)+z*Math.sin(turn))*scale,y-(b-mouth+.5)*scale,z*Math.cos(turn)-a*Math.sin(turn)]});const faces=mesh.f.slice().sort((a,b)=>a.reduce((s,i)=>s+points[i][2],0)-b.reduce((s,i)=>s+points[i][2],0));for(const f of faces){if(f.some(i=>!points[i]))continue;const a=mesh.v[f[0]],b=mesh.v[f[1]],c=mesh.v[f[2]],u=b.map((v,i)=>v-a[i]),v=c.map((q,i)=>q-a[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],len=Math.hypot(...n)||1,light=.16+.7*Math.max(0,(-n[0]*.45+n[1]*.3+Math.abs(n[2])*.82)/len);ctx.fillStyle=`rgb(${Math.round(28*light)},${Math.round(135*light)},${Math.round(154*light)})`;ctx.strokeStyle='rgba(103,230,236,.13)';ctx.lineWidth=.5;ctx.beginPath();f.forEach((i,j)=>j?ctx.lineTo(points[i][0],points[i][1]):ctx.moveTo(points[i][0],points[i][1]));ctx.closePath();ctx.fill();ctx.stroke();}ctx.strokeStyle='rgba(105,244,242,.8)';ctx.shadowColor='#4aeeee';ctx.shadowBlur=8;ctx.lineWidth=1.2;for(const eye of [[33,160,158,133,153,144],[263,387,385,362,380,373]]){ctx.beginPath();eye.forEach((i,j)=>j?ctx.lineTo(points[i][0],points[i][1]):ctx.moveTo(points[i][0],points[i][1]));ctx.closePath();ctx.stroke();}ctx.shadowBlur=0;frame++;if(intensity>0)raf=requestAnimationFrame(draw);return;}
 ctx.save();ctx.translate(x,y);for(let j=0;j<8;j++){ctx.save();ctx.rotate((j%2?1:-1)*t*(active?2:1)+j*.37);ctx.strokeStyle=`rgba(${color},${j===2?.5:.08+j*.018})`;ctx.lineWidth=j===2?1.2:.65;ctx.beginPath();ctx.ellipse(0,0,r*(.7+j*.055),r*(.38+j*.077),j*.3,0,Math.PI*2);ctx.stroke();ctx.restore();}
 for(let i=0;i<100;i++){let a=i*Math.PI*2/100;let wave=(state==='speaking'||state==='listening')?amplitude.current*22*(.5+.5*Math.sin(i*.8+frame*.2)):0;let inner=r*1.11,outer=inner+(i%5===0?8:3)+wave;ctx.strokeStyle=`rgba(${color},${i%5===0?.5:.16})`;ctx.beginPath();ctx.moveTo(Math.cos(a)*inner,Math.sin(a)*inner);ctx.lineTo(Math.cos(a)*outer,Math.sin(a)*outer);ctx.stroke();}
 for(let j=0;j<3;j++){ctx.save();ctx.rotate(t*(j+1)*(j%2?-1:1));ctx.strokeStyle=`rgba(${color},.7)`;ctx.shadowColor=`rgb(${color})`;ctx.shadowBlur=12;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,r*(.76+j*.12),j*2,j*2+.55);ctx.stroke();ctx.restore();}
 ctx.fillStyle=`rgba(${color},.5)`;for(let j=0;j<18;j++){const a=j*2.399+t*.3,rad=r*(.18+.67*((j*7%19)/19));ctx.beginPath();ctx.arc(Math.cos(a)*rad,Math.sin(a)*rad,1,0,7);ctx.fill();}ctx.restore();frame++;if(intensity>0||state==='speaking'||state==='listening')raf=requestAnimationFrame(draw);};draw();return()=>cancelAnimationFrame(raf);},[state,intensity,variant,mesh]);
 return <div className={'core-visual core-'+state}><canvas ref={canvas}/><div className="core-word" style={{display:variant==='face'?'none':undefined}}><strong>JARVIS</strong><span>PERSONAL INTELLIGENCE</span></div></div>;
}
