'use client';
import {useState} from 'react';
import {Activity,Command,Settings,Shield,ChevronDown,PanelRightClose,PanelRightOpen} from 'lucide-react';
export function Navigation({items,page,onGo,running,collapsed,onCollapse}:{items:[string,string,typeof Activity][];page:string;onGo:(page:any)=>void;running:number;collapsed:boolean;onCollapse:()=>void}){
 const [tools,setTools]=useState(false);
 const primary=['command','tasks','knowledge','focus'];
 const button=([id,label,Icon]:[string,string,typeof Activity])=><button key={id} className={page===id?'active':''} aria-current={page===id?'page':undefined} title={label} onClick={()=>onGo(id)}><Icon size={20}/><span>{label}</span>{id==='tasks'&&running>0&&<b>{running}</b>}</button>;
 return <aside className="sidebar"><a className="brand" href="#command" onClick={()=>onGo('command')}><span className="brand-emblem"><Command size={26}/></span><span><strong>JARVIS</strong><small>המרחב האישי שלך</small></span></a><button className="collapse" onClick={onCollapse} aria-label={collapsed?'הרחבת תפריט':'קיפול תפריט'}>{collapsed?<PanelRightOpen size={19}/>:<PanelRightClose size={19}/>}</button><nav aria-label="מסכי ג׳רוויס"><div className="nav-group"><span className="nav-label">סביבת עבודה</span>{items.filter(i=>primary.includes(i[0])).map(button)}</div><div className="nav-group"><button className="nav-section-toggle" onClick={()=>setTools(!tools)} aria-expanded={tools}><span>כלים וחיבורים</span><ChevronDown size={16} style={{transform:tools?'rotate(0deg)':'rotate(90deg)'}}/></button>{tools&&items.filter(i=>!primary.includes(i[0])).map(button)}</div></nav><div className="sidebar-bottom"><button onClick={()=>onGo('permissions')} className={page==='permissions'?'active':''} title="גישה למחשב"><Shield size={20}/><span>גישה למחשב</span></button><button onClick={()=>onGo('settings')} className={page==='settings'?'active':''} title="הגדרות"><Settings size={20}/><span>הגדרות</span></button><button onClick={()=>onGo('debug')} className={page==='debug'?'active':''} title="אבחון מערכת"><Activity size={20}/><span>אבחון מערכת</span></button><div className="commander"><span>A</span><div><small>ברוך הבא</small><b>אדוני</b></div><Shield size={18}/></div></div></aside>
}
